// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.punyco.thirtytwosquare.domain;

import de.punyco.thirtytwosquare.domain.Squarelet;
import java.io.Serializable;

privileged aspect Squarelet_Roo_Serializable {
    
    declare parents: Squarelet implements Serializable;
    
    private static final long Squarelet.serialVersionUID = 1L;
    
}
