// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.punyco.thirtytwosquare.domain;

import de.punyco.thirtytwosquare.domain.Squarelet;

privileged aspect Squarelet_Roo_JavaBean {
    
    public String Squarelet.getMetadata() {
        return this.metadata;
    }
    
    public void Squarelet.setMetadata(String metadata) {
        this.metadata = metadata;
    }
    
}
