// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.punyco.thirtytwosquare.domain;

import de.punyco.thirtytwosquare.domain.UserAccount;
import java.io.Serializable;

privileged aspect UserAccount_Roo_Serializable {
    
    declare parents: UserAccount implements Serializable;
    
    private static final long UserAccount.serialVersionUID = 1L;
    
}
