// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.punyco.thirtytwosquare.domain.appengine;

import de.punyco.thirtytwosquare.domain.appengine.GAEUserAccount;
import javax.persistence.Entity;

privileged aspect GAEUserAccount_Roo_Jpa_Entity {
    
    declare @type: GAEUserAccount: @Entity;
    
}
