// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.punyco.thirtytwosquare.domain;

import de.punyco.thirtytwosquare.domain.SquareletDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SquareletDataOnDemand_Roo_Configurable {
    
    declare @type: SquareletDataOnDemand: @Configurable;
    
}
